"""add web security monitoring

Revision ID: 3f1186d33919
Revises: 673a0121be01
Create Date: 2026-08-17 17:18:47.707311
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3f1186d33919"
down_revision: str | None = "673a0121be01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=False),
        sa.Column("target_host", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=12), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("query_string", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_bytes", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("safe_headers", sa.JSON(), nullable=False),
        sa.Column("body_excerpt", sa.Text(), nullable=True),
        sa.Column("session_hash", sa.String(length=64), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("upstream_signals", sa.JSON(), nullable=False),
        sa.Column("request_metadata", sa.JSON(), nullable=False),
        sa.Column("security_event_id", sa.String(length=36), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_event_id"],
            ["security_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("security_event_id"),
    )
    op.create_index(op.f("ix_web_requests_method"), "web_requests", ["method"], unique=False)
    op.create_index(op.f("ix_web_requests_request_id"), "web_requests", ["request_id"], unique=True)
    op.create_index(op.f("ix_web_requests_session_hash"), "web_requests", ["session_hash"], unique=False)
    op.create_index(op.f("ix_web_requests_source_ip"), "web_requests", ["source_ip"], unique=False)
    op.create_index(op.f("ix_web_requests_status_code"), "web_requests", ["status_code"], unique=False)
    op.create_index(op.f("ix_web_requests_target_host"), "web_requests", ["target_host"], unique=False)
    op.create_index(op.f("ix_web_requests_timestamp"), "web_requests", ["timestamp"], unique=False)
    op.create_index(op.f("ix_web_requests_username"), "web_requests", ["username"], unique=False)
    op.create_table(
        "attack_detections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attack_key", sa.String(length=255), nullable=False),
        sa.Column("attack_type", sa.String(length=80), nullable=False),
        sa.Column("family", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("classification", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=False),
        sa.Column("target_host", sa.String(length=255), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule_id", sa.String(length=100), nullable=False),
        sa.Column("alert_id", sa.String(length=36), nullable=True),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("primary_event_id", sa.String(length=36), nullable=False),
        sa.Column("related_event_ids", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("mitre_techniques", sa.JSON(), nullable=False),
        sa.Column("response_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_event_id"],
            ["security_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["detection_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alert_id"),
    )
    op.create_index(op.f("ix_attack_detections_attack_key"), "attack_detections", ["attack_key"], unique=True)
    op.create_index(op.f("ix_attack_detections_attack_type"), "attack_detections", ["attack_type"], unique=False)
    op.create_index(op.f("ix_attack_detections_classification"), "attack_detections", ["classification"], unique=False)
    op.create_index(op.f("ix_attack_detections_family"), "attack_detections", ["family"], unique=False)
    op.create_index(op.f("ix_attack_detections_first_seen"), "attack_detections", ["first_seen"], unique=False)
    op.create_index(op.f("ix_attack_detections_incident_id"), "attack_detections", ["incident_id"], unique=False)
    op.create_index(op.f("ix_attack_detections_last_seen"), "attack_detections", ["last_seen"], unique=False)
    op.create_index(
        op.f("ix_attack_detections_primary_event_id"), "attack_detections", ["primary_event_id"], unique=False
    )
    op.create_index(op.f("ix_attack_detections_rule_id"), "attack_detections", ["rule_id"], unique=False)
    op.create_index(op.f("ix_attack_detections_severity"), "attack_detections", ["severity"], unique=False)
    op.create_index(op.f("ix_attack_detections_source_ip"), "attack_detections", ["source_ip"], unique=False)
    op.create_index(op.f("ix_attack_detections_status"), "attack_detections", ["status"], unique=False)
    op.create_index(op.f("ix_attack_detections_target_host"), "attack_detections", ["target_host"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attack_detections_target_host"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_status"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_source_ip"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_severity"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_rule_id"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_primary_event_id"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_last_seen"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_incident_id"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_first_seen"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_family"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_classification"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_attack_type"), table_name="attack_detections")
    op.drop_index(op.f("ix_attack_detections_attack_key"), table_name="attack_detections")
    op.drop_table("attack_detections")
    op.drop_index(op.f("ix_web_requests_username"), table_name="web_requests")
    op.drop_index(op.f("ix_web_requests_timestamp"), table_name="web_requests")
    op.drop_index(op.f("ix_web_requests_target_host"), table_name="web_requests")
    op.drop_index(op.f("ix_web_requests_status_code"), table_name="web_requests")
    op.drop_index(op.f("ix_web_requests_source_ip"), table_name="web_requests")
    op.drop_index(op.f("ix_web_requests_session_hash"), table_name="web_requests")
    op.drop_index(op.f("ix_web_requests_request_id"), table_name="web_requests")
    op.drop_index(op.f("ix_web_requests_method"), table_name="web_requests")
    op.drop_table("web_requests")
    # ### end Alembic commands ###
