from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class WebAttackDefinition:
    number: int
    slug: str
    name: str
    family: str
    severity: str
    base_confidence: float
    detection_mode: str
    mitre: tuple[str, ...]
    description: str
    patterns: tuple[str, ...] = ()

    @property
    def rule_id(self) -> str:
        return f"GS-WEB-{self.number:03d}"

    def view(self) -> dict[str, object]:
        result = asdict(self)
        result["rule_id"] = self.rule_id
        result["mitre"] = list(self.mitre)
        result["patterns"] = len(self.patterns)
        return result


# Pattern matching is deliberately conservative. Context-dependent categories are
# detected from explicit WAF/application signals and behavioral aggregation rather
# than pretending an access log alone proves exploitation.
WEB_ATTACK_CATALOG: tuple[WebAttackDefinition, ...] = (
    WebAttackDefinition(
        1,
        "sql_injection",
        "SQL Injection",
        "INJECTION",
        "HIGH",
        0.72,
        "SIGNATURE_OR_SIGNAL",
        ("T1190",),
        "SQL metacharacters and common injection operators in request input.",
        (
            r"(?:\bunion\s+(?:all\s+)?select\b|\bor\s+['\d]+\s*=\s*['\d]+|\bsleep\s*\(|\bwaitfor\s+delay\b|information_schema|(?:--|#)\s*$)",
        ),
    ),
    WebAttackDefinition(
        2,
        "xss",
        "Cross-Site Scripting (XSS)",
        "CLIENT_SIDE",
        "HIGH",
        0.72,
        "SIGNATURE_OR_SIGNAL",
        ("T1189",),
        "Script-capable markup or browser event handlers in untrusted input.",
        (r"(?:<\s*script\b|javascript\s*:|on(?:error|load|click|mouseover)\s*=|<\s*(?:img|svg|iframe)\b)",),
    ),
    WebAttackDefinition(
        3,
        "csrf",
        "Cross-Site Request Forgery (CSRF)",
        "CLIENT_SIDE",
        "HIGH",
        0.76,
        "CONTEXT_SIGNAL",
        ("T1190",),
        "Requires application/WAF evidence of a missing or invalid anti-CSRF control.",
    ),
    WebAttackDefinition(
        4,
        "idor",
        "IDOR / Broken Access Control",
        "AUTHORIZATION",
        "HIGH",
        0.78,
        "CONTEXT_SIGNAL",
        ("T1190",),
        "Requires authorization context showing access to another object's identifier.",
    ),
    WebAttackDefinition(
        5,
        "brute_force",
        "Brute-Force Attack",
        "AUTHENTICATION",
        "HIGH",
        0.65,
        "BEHAVIORAL_OR_SIGNAL",
        ("T1110",),
        "Repeated authentication failures from one source.",
    ),
    WebAttackDefinition(
        6,
        "credential_stuffing",
        "Credential Stuffing",
        "AUTHENTICATION",
        "CRITICAL",
        0.76,
        "BEHAVIORAL_OR_SIGNAL",
        ("T1110.004",),
        "Repeated known-account authentication attempts across distributed sources.",
    ),
    WebAttackDefinition(
        7,
        "password_spraying",
        "Password Spraying",
        "AUTHENTICATION",
        "HIGH",
        0.74,
        "BEHAVIORAL_OR_SIGNAL",
        ("T1110.003",),
        "One source attempts authentication against multiple accounts.",
    ),
    WebAttackDefinition(
        8,
        "session_hijacking",
        "Session Hijacking",
        "AUTHENTICATION",
        "CRITICAL",
        0.82,
        "CONTEXT_SIGNAL",
        ("T1539",),
        "Requires session reuse, binding, or impossible-transition evidence.",
    ),
    WebAttackDefinition(
        9,
        "command_injection",
        "Command Injection",
        "INJECTION",
        "CRITICAL",
        0.82,
        "SIGNATURE_OR_SIGNAL",
        ("T1059",),
        "Shell separators or command-substitution constructs in request input.",
        (r"(?:;|\|\||&&)\s*(?:cat|id|whoami|curl|wget|bash|sh|powershell)\b|`[^`]+`|\$\([^)]*\)",),
    ),
    WebAttackDefinition(
        10,
        "path_traversal",
        "Path Traversal",
        "SERVER_FILE",
        "HIGH",
        0.78,
        "SIGNATURE_OR_SIGNAL",
        ("T1190",),
        "Parent-directory traversal or encoded traversal sequences.",
        (r"(?:\.\./|\.\.\\|%2e%2e(?:%2f|/|%5c)|%252e%252e)",),
    ),
    WebAttackDefinition(
        11,
        "malicious_file_upload",
        "Malicious File Upload",
        "SERVER_FILE",
        "CRITICAL",
        0.84,
        "CONTEXT_OR_SIGNATURE",
        ("T1105",),
        "Executable/script upload or application malware-scan signal.",
        (r"filename\s*=.*\.(?:php\d*|phtml|jsp|aspx?|exe|dll|sh|ps1)(?:[\s\";]|$)",),
    ),
    WebAttackDefinition(
        12,
        "ssrf",
        "Server-Side Request Forgery (SSRF)",
        "SERVER_FILE",
        "CRITICAL",
        0.82,
        "SIGNATURE_OR_SIGNAL",
        ("T1190",),
        "Requests targeting loopback, link-local metadata, or internal schemes.",
        (
            r"(?:https?://)?(?:127\.0\.0\.1|localhost|169\.254\.169\.254|0\.0\.0\.0|\[?::1\]?)(?::|/|$)|(?:file|gopher|dict)://",
        ),
    ),
    WebAttackDefinition(
        13,
        "security_misconfiguration",
        "Security Misconfiguration",
        "SERVER_FILE",
        "MEDIUM",
        0.72,
        "CONFIGURATION_SIGNAL",
        ("T1190",),
        "Scanner or configuration audit signal for an exposed insecure setting.",
    ),
    WebAttackDefinition(
        14,
        "information_disclosure",
        "Information Disclosure",
        "SERVER_FILE",
        "HIGH",
        0.76,
        "SIGNATURE_OR_SIGNAL",
        ("T1552",),
        "Sensitive files, debug endpoints, stack traces, or secret disclosure.",
        (r"/(?:\.env|\.git/|server-status|phpinfo\.php|actuator/env|debug/vars|swagger\.json)(?:\?|$)",),
    ),
    WebAttackDefinition(
        15,
        "open_redirect",
        "Open Redirect",
        "CLIENT_SIDE",
        "MEDIUM",
        0.66,
        "SIGNATURE_OR_SIGNAL",
        ("T1189",),
        "External redirect target supplied through common redirect parameters.",
        (r"(?:redirect|return|next|url|continue)=(?:https?%3a|https?://|//)",),
    ),
    WebAttackDefinition(
        16,
        "xxe",
        "XML External Entity (XXE)",
        "INJECTION",
        "CRITICAL",
        0.88,
        "SIGNATURE_OR_SIGNAL",
        ("T1190",),
        "DOCTYPE/ENTITY declarations with external resource resolution.",
        (r"<!doctype[^>]+\[|<!entity\s+[^>]+system\s+['\"]",),
    ),
    WebAttackDefinition(
        17,
        "insecure_deserialization",
        "Insecure Deserialization",
        "SERVER_FILE",
        "CRITICAL",
        0.86,
        "SIGNATURE_OR_SIGNAL",
        ("T1190",),
        "Serialized-object markers or upstream unsafe-deserialization signal.",
        (r"(?:rO0AB|aced0005|O:\d+:\"|gASV[A-Za-z0-9_/+-]+|__reduce__)",),
    ),
    WebAttackDefinition(
        18,
        "http_request_smuggling",
        "HTTP Request Smuggling",
        "HTTP_API",
        "CRITICAL",
        0.9,
        "HEADER_OR_SIGNAL",
        ("T1190",),
        "Conflicting transfer framing or proxy parser disagreement.",
        (r"transfer-encoding[^\n]*chunked[\s\S]*content-length|content-length[^\n]*[\r\n]+content-length",),
    ),
    WebAttackDefinition(
        19,
        "business_logic_abuse",
        "Business Logic Abuse",
        "AUTHORIZATION",
        "HIGH",
        0.78,
        "CONTEXT_OR_BEHAVIOR",
        ("T1190",),
        "Application-defined invariant, sequence, quantity, or workflow violation.",
    ),
    WebAttackDefinition(
        20,
        "api_attack",
        "API Attack",
        "HTTP_API",
        "HIGH",
        0.7,
        "SIGNATURE_BEHAVIOR_SIGNAL",
        ("T1190",),
        "Unauthorized sensitive API access, enumeration, or malformed method activity.",
        (r"/api/(?:admin|internal|debug|users/export|keys)(?:/|\?|$)",),
    ),
    WebAttackDefinition(
        21,
        "host_header_injection",
        "Host Header Injection",
        "HTTP_API",
        "HIGH",
        0.78,
        "HEADER_OR_SIGNAL",
        ("T1190",),
        "Forwarded/host header conflicts or invalid external authority.",
        (r"x-forwarded-host[^\n]*(?:localhost|127\.0\.0\.1|\.invalid)",),
    ),
    WebAttackDefinition(
        22,
        "http_parameter_pollution",
        "HTTP Parameter Pollution",
        "INJECTION",
        "MEDIUM",
        0.68,
        "STRUCTURE_OR_SIGNAL",
        ("T1190",),
        "Repeated security-relevant parameter names with conflicting values.",
        (r"(?:^|[?&])(?:id|role|admin|redirect|url)=[^&]*(?:&(?:[^&]*&)*)(?:id|role|admin|redirect|url)=",),
    ),
    WebAttackDefinition(
        23,
        "clickjacking",
        "Clickjacking",
        "CLIENT_SIDE",
        "MEDIUM",
        0.7,
        "CONFIGURATION_SIGNAL",
        ("T1189",),
        "Requires response-policy evidence that framing protections are absent.",
    ),
    WebAttackDefinition(
        24,
        "web_cache_poisoning",
        "Web Cache Poisoning",
        "CACHE_INFRASTRUCTURE",
        "HIGH",
        0.78,
        "HEADER_BEHAVIOR_SIGNAL",
        ("T1190",),
        "Unkeyed input manipulates cacheable responses.",
    ),
    WebAttackDefinition(
        25,
        "web_cache_deception",
        "Web Cache Deception",
        "CACHE_INFRASTRUCTURE",
        "HIGH",
        0.76,
        "CONTEXT_SIGNAL",
        ("T1190",),
        "Private dynamic content is exposed through a cacheable-looking path.",
    ),
    WebAttackDefinition(
        26,
        "prototype_pollution",
        "Prototype Pollution",
        "CLIENT_SIDE",
        "HIGH",
        0.8,
        "SIGNATURE_OR_SIGNAL",
        ("T1190",),
        "Prototype mutation keys in JSON or request parameters.",
        (r"(?:__proto__|constructor\s*\[\s*prototype\s*\]|prototype\s*\[)",),
    ),
    WebAttackDefinition(
        27,
        "ssti",
        "Server-Side Template Injection (SSTI)",
        "INJECTION",
        "CRITICAL",
        0.84,
        "SIGNATURE_OR_SIGNAL",
        ("T1190",),
        "Common server-template expression delimiters and probes.",
        (r"(?:\{\{\s*\d+\s*[+*]\s*\d+\s*\}\}|\$\{\s*\d+\s*[+*]\s*\d+\s*\}|<%=\s*\d+)",),
    ),
    WebAttackDefinition(
        28,
        "lfi",
        "Local File Inclusion (LFI)",
        "INJECTION",
        "CRITICAL",
        0.84,
        "SIGNATURE_OR_SIGNAL",
        ("T1190",),
        "Local sensitive file references in inclusion parameters.",
        (r"(?:/etc/passwd|/proc/self/environ|windows/win\.ini|boot\.ini)",),
    ),
    WebAttackDefinition(
        29,
        "rfi",
        "Remote File Inclusion (RFI)",
        "INJECTION",
        "CRITICAL",
        0.84,
        "SIGNATURE_OR_SIGNAL",
        ("T1105",),
        "Remote URL supplied to file/template/include parameters.",
        (r"(?:file|page|template|include|path)=(?:https?%3a|https?://|//)",),
    ),
    WebAttackDefinition(
        30,
        "race_condition",
        "Race Condition Attack",
        "CACHE_INFRASTRUCTURE",
        "HIGH",
        0.76,
        "BEHAVIORAL_OR_SIGNAL",
        ("T1190",),
        "Concurrent duplicate state-changing requests against one resource.",
    ),
    WebAttackDefinition(
        31,
        "cors_misconfiguration",
        "CORS Misconfiguration",
        "HTTP_API",
        "HIGH",
        0.78,
        "CONFIGURATION_SIGNAL",
        ("T1190",),
        "Requires response-header evidence of unsafe cross-origin trust.",
    ),
    WebAttackDefinition(
        32,
        "jwt_attack",
        "JWT Attack",
        "AUTHENTICATION",
        "CRITICAL",
        0.86,
        "SIGNATURE_OR_SIGNAL",
        ("T1539",),
        "Algorithm confusion, unsigned token, or token-validation failure signal.",
        (r"(?:\"alg\"\s*:\s*\"none\"|eyJhbGciOiJub25lI)",),
    ),
    WebAttackDefinition(
        33,
        "api_rate_limit_bypass",
        "API Rate-Limit Bypass",
        "HTTP_API",
        "HIGH",
        0.74,
        "BEHAVIORAL_OR_SIGNAL",
        ("T1499",),
        "Sustained request volume or identity/header variation intended to evade limits.",
    ),
    WebAttackDefinition(
        34,
        "graphql_attack",
        "GraphQL Attack",
        "HTTP_API",
        "HIGH",
        0.76,
        "SIGNATURE_OR_SIGNAL",
        ("T1190",),
        "Introspection, excessive aliases/depth, batching, or mutation abuse.",
        (r"(?:__schema|__type\s*\(|query\s+IntrospectionQuery|mutation\s*\{|(?:alias\d+\s*:){5,})",),
    ),
    WebAttackDefinition(
        35,
        "websocket_attack",
        "WebSocket Attack",
        "HTTP_API",
        "HIGH",
        0.76,
        "PROTOCOL_OR_SIGNAL",
        ("T1190",),
        "Unauthorized upgrade, origin violation, or malicious frame signal.",
    ),
)

ATTACK_BY_SLUG = {item.slug: item for item in WEB_ATTACK_CATALOG}
ATTACK_BY_NAME = {item.name.lower(): item for item in WEB_ATTACK_CATALOG}


def resolve_attack_signal(value: str) -> WebAttackDefinition | None:
    normalized = value.strip().lower().replace("-", "_").replace(" ", "_")
    if normalized in ATTACK_BY_SLUG:
        return ATTACK_BY_SLUG[normalized]
    return ATTACK_BY_NAME.get(value.strip().lower())
